export { default as Yatika } from "./yatika.jpeg";
export { default as Annika } from "./Annika.jpeg";
export { default as Ananya } from "./Ananya.jpeg";
export { default as Saanvi } from "./Saanvi.jpeg";
export { default as Meenal } from "./Meenal.jpeg";
export { default as Bhawana } from "./Bhawana.jpeg";
export { default as Tanish } from "./Tanish.jpeg";
export { default as Navya } from "./Navya.jpeg";
export { default as Srishti } from "./Srishti.jpeg";
export { default as Rohan } from "./Rohan.jpeg";
export { default as Tia } from "./Tia.jpeg";
export { default as Atharv } from "./Atharv.jpeg";
export { default as Arshia } from "./Arshia.jpeg";
// export { default as Aryan } from "./Aryan.jpeg";
export { default as Devansh } from "./Devansh.jpeg";
export { default as Anirudh } from "./Anirudh.jpeg";
export { default as Ishant } from "./Ishant.jpeg";
export { default as Mahika } from "./Mahika.jpeg";